steps:
  - id: "Build do source em Go"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['install', 'server']
    env: ['GOPATH=./']

  - id: "Teste do compilado"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['test', 'server']
    env: ['GOPATH=./']

  - id: "Building image from Dockerfile.prod"
    name: "gcr.io/cloud-builders/docker"
    args: ['build','-t','gcr.io/$PROJECT_ID/go-server','-f','Dockerfile','.']

  - id: "Pushing image"
    name: "gcr.io/cloud-builders/docker"
    args: ['push','gcr.io/$PROJECT_ID/go-server']

