apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: docker.io/aleckzts/go-server
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"